server:
  contextPath: /spring-security-oauth-server
  port: 8081
  ssl:
    key-store: classpath:server.jks
    key-store-password: password
    key-password: password
spring:
  application:
    name: auth-server
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false