spring:
  cloud:
    config:
      uri: https://config-server:8888
      discovery:
        serviceId: config-server
  rabbitmq:
    host: rabbitmq
    port: 5672
eureka:
  instance:
    prefer-ip-address: false
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: eureka-service
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://eureka-service:8761/eureka/