spring:
  cloud:
    config:
      uri: http://config-server:8888
      discovery:
        serviceId: config-server
eureka:
  instance:
    prefer-ip-address: false
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: eureka-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
spring:
  rabbitmq:
    host: rabbitmq