spring:
  cloud:
    config:
      uri: https://localhost:8888
      discovery:
        serviceId: config-server
  rabbitmq:
    host: localhost
    port: 5672
eureka:
  instance:
    hostname: eureka-service
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
  server:
    enable-self-preservation: false