spring:
  application:
    name: eureka-service
server:
  port: 8761
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-alias: localhost
    trust-store: classpath:truststore.jks
    trust-store-password: password
    client-auth: want
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
security:
  basic:
    enabled: false