spring:
  cloud:
    config:
      uri: https://config-server:8888
      discovery:
        serviceId: config-server
  rabbitmq:
    host: rabbitmq
eureka:
  instance:
    prefer-ip-address: false
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: eureka-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://eureka-service:8761/eureka/
server:
  port: 8761
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password
    key-alias: localhost
    trust-store: classpath:truststore.jks
    trust-store-password: password