spring:
  cloud:
    config:
      uri: http://localhost:8888
      discovery:
        serviceId: config-server
  rabbitmq:
    host: localhost
eureka:
  instance:
    hostname: eureka-service
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false