spring:
  cloud:
    config:
      uri: https://localhost:8888
      discovery:
        serviceId: config-server
  rabbitmq:
    host: localhost
    port: 5672
  datasource:
    initialize: false
    url: jdbc:postgresql://localhost:5432/shop
    username: sysadm
    password: sysadm
    driver-class-name: org.postgresql.Driver
eureka:
  instance:
    hostname: shop-service
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
    secureVirtualHostName: ${spring.application.name}
  client:
    eureka-connection-idle-timeout-seconds: 3000
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
security:
  oauth2:
    resource:
      user-info-uri: https://localhost:8081/spring-security-oauth-server/user