spring:
  application:
    name: shop-service
  jpa:
    show_sql: true
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: none
    database: POSTGRESQL
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ALL
      hibernate:
        cache:
          use_query_cache: false
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  cloud:
    config:
      discovery:
        enabled: true
  resources:
    chain:
      enabled: true
  cache:
    ehcache:
      config: classpath:ehcache.xml
ribbon:
  ReadTimeout: 18000000
  ConnectTimeout: 18000000
  eureka:
    enabled: true
jwt:
  header: AuthHeader
  key: e038394bc945eed83ca8797aae26fddfae91b175fc4dd26339dd6cb8066c65b892d6ac07c0a3c0384601896ade90551905460af66e4864e9c71a31d6d523c136
  expiration: 36000
encrypt:
  failOnError: false
logging:
  file: log.txt
  level: error
server:
  port: 9000
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password
    key-alias: localhost
    trust-store: classpath:truststore.jks
    trust-store-password: password
management:
  security:
    enabled: false