spring:
  cloud:
    config:
      uri: https://config-server:8888
      discovery:
        serviceId: config-server
  rabbitmq:
    host: rabbitmq
  jpa:
    show_sql: false
  datasource:
    initialize: false
    url: jdbc:postgresql://shopdb:5432/shop
    username: sysadm
    password: sysadm
    driver-class-name: org.postgresql.Driver
eureka:
  instance:
    hostname: shop-service
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
    secureVirtualHostName: ${spring.application.name}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    eureka-connection-idle-timeout-seconds: 3000
    serviceUrl:
      defaultZone: https://eureka-service:8761/eureka/
security:
  oauth2:
    resource:
      user-info-uri: https://auth-server:8081/spring-security-oauth-server/user