spring:
  cloud:
    config:
      uri: http://localhost:8888
      discovery:
        serviceId: config-server
  datasource:
    initialize: false
    url: jdbc:postgresql://localhost:5432/shop
    username: sysadm
    password: sysadm
    driver-class-name: org.postgresql.Driver
server:
  port: 9000
eureka:
  instance:
    hostname: shop-service
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    nonSecurePort: ${server.port}
  client:
    eureka-connection-idle-timeout-seconds: 3000
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  rabbitmq:
    host: localhost
security:
  basic:
    enabled: false
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:8081/oauth/token_key