eureka:
  instance:
    hostname: turbine-server
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
    nonSecurePort: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    eureka-connection-idle-timeout-seconds: 6000
    serviceUrl:
      defaultZone: https://eureka-service:8761/eureka/
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
turbine:
  amqp:
    port: 8989
server:
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-alias: localhost
    trust-store: classpath:truststore.jks
    trust-store-password: password