eureka:
  instance:
    hostname: turbine-server
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
    nonSecurePort: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    eureka-connection-idle-timeout-seconds: 6000
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672