eureka:
  instance:
    hostname: ${PREFIX:}${spring.application.name}.${application.domain:cfapps.io}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    eureka-connection-idle-timeout-seconds: 6000
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:https://${PREFIX:}eureka.${application.domain:cfapps.io}}/eureka/
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
server:
  port: 0 # Avoid collisions in the unknown CF djungle...
  ssl:
    trust-store: classpath:truststore.jks
    trust-store-password: password

management:
  port: 0 # Avoid collisions in the unknown CF djungle...

turbine:
  amqp:
    port: 0 # Avoid collisions in the unknown CF djungle...