eureka:
  instance:
    hostname: turbine-server
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
  client:
    eureka-connection-idle-timeout-seconds: 3000
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
spring:
  rabbitmq:
    host: localhost
    port: 5672
turbine:
  amqp:
    port: 8989
server:
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-alias: localhost
    trust-store: classpath:truststore.jks
    trust-store-password: password