spring:
  cloud:
    config:
      uri: ${vcap.services.${PREFIX:}config-server.credentials.uri:https://${PREFIX:}${config-server.${application.domain:cfapps.io}}}
      discovery:
        serviceId: config-server
      fail-fast: true
  rabbitmq:
    host: rabbitmq
    port: 5672