spring:
  application:
    name: zipkin-server
  http:
    multipart:
      max-file-size: 25600MB
      max-request-size: 25600MB
server:
  port: 9411
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-alias: localhost
    trust-store: classpath:truststore.jks
    trust-store-password: password
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
security:
  basic:
    enabled: false