eureka:
  instance:
    hostname: zuul-proxy
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
    secureVirtualHostName: ${spring.application.name}
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    eureka-connection-idle-timeout-seconds: 6000
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
zuul:
  ssl-hostname-validation-enabled: false
  ignoredServices: "*"
  routes:
    shop-service:
      path: /shop/**
      serviceId: shop-service
spring:
  rabbitmq:
    host: localhost
security:
  oauth2:
    resource:
      user-info-uri: https://localhost:8081/spring-security-oauth-server/user