spring:
  application:
    name: shop-service
  http:
    multipart:
      max-file-size: 25600MB
      max-request-size: 25600MB
server:
  port: 8080
  ssl:
    key-store: classpath:server.jks
    key-store-password: password
    key-password: password
    trust-store: src/main/resources/truststore.jks
    trust-store-password: password
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false