eureka:
  instance:
    hostname: zuul-proxy
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
     non-secure-port-enabled: false
     secure-port-enabled: true
     secure-port: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    eureka-connection-idle-timeout-seconds: 6000
    serviceUrl:
      defaultZone: https://eureka-service:8761/eureka/
zuul:
  ignoredServices: "*"
  routes:
    shop-service:
      path: /shop/**
      serviceId: shop-service
      url: https://shop-service:9000/
spring:
  rabbitmq:
    host: rabbitmq
security:
  oauth2:
    resource:
      user-info-uri: httpss://auth-server:8081/spring-security-oauth-server/user
server:
  ssl:
    trust-store: truststore.jks